### PR TITLE
* Creating a public static ParseOptions to wrap calls to singleton

### LINKED ISSUE #1: use static class methods to wrap calls to singleton
so that `CmdLineOptions::instanceGet()->ParseOptions()` is just `CmdLineOptions::ParseOptions()`

also what is the normal

### PR DESCRIPTION
**Pull request by pointnotfoe**
* Renaming existing ParseOptions to ParseOptionsInternal

### CODE REVIEW

**Comment by pointnotfoe** [comment]
how to build? only on linux? windows?

**Comment by pointnotfoe** [comment]
> how to build? only on linux? windows?
found it
https://github.com/byronwatt/CmdLineOptions/pull/12/files

**Review by byronwatt — APPROVED** [review]
awesome!

**Comment by byronwatt** [comment]
do you have the squash and merge button, or do i need to update permissions ?

note: i didn't notice when you created the branch, nor the pull request,... there are so many emails created, i just created a filter to not have them land in my in-box.

**Comment by pointnotfoe** [comment]
dont see it anything for squashing or merging...
ya might need to do the same.. too many emails

**Pull request merged**
